// Generated by CoffeeScript 1.6.3
(function() {
  var Shopper;

  Shopper = window.Shopper = window.Shopper || {};

  Shopper.getCps = function() {
    if (Game.recalculateGains) {
      Game.CalculateGains();
    }
    return Game.cookiesPs;
  };

  Shopper.cpsGainUnsafe = function(item) {
    var initialCps;
    initialCps = Shopper.getCps();
    Game.Earn(item.price || item.basePrice);
    item.buy();
    return Shopper.getCps() - initialCps;
  };

  Shopper.cpsGain = function(item) {
    return Shopper.safeCall(function() {
      return Shopper.cpsGainUnsafe(item);
    });
  };

  Shopper.cpsGainPerSecond = function(item) {
    return Shopper.cpsGain(item) * Shopper.getCps() / (item.price || item.basePrice);
  };

}).call(this);
